# Generated by Django 3.2.20 on 2023-08-24 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productsApi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to='product_image/'),
        ),
    ]
