# Generated by Django 3.2.20 on 2023-08-24 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productsApi', '0002_alter_products_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='images',
        ),
    ]
