# Generated by Django 3.2.20 on 2023-08-24 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productsApi', '0003_remove_products_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to='products_image/'),
        ),
    ]
