# Generated by Django 3.2.20 on 2023-08-24 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productsApi', '0004_products_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='images',
            field=models.URLField(blank=True, null=True),
        ),
    ]
